apiVersion: v2
name: fluentd
description: A Helm chart for Kubernetes
# type: application
## version and appVersion changed from upstream
version: 0.5.3-bb.3
appVersion: 1.19.0
icon: https://www.fluentd.org/images/miscellany/fluentd-logo_2x.png
home: https://www.fluentd.org/
sources:
  - https://github.com/fluent/fluentd/
  - https://github.com/fluent/fluentd-kubernetes-daemonset
dependencies:
  - name: fluentd
    version: 0.5.3
    repository: https://fluent.github.io/helm-charts
    alias: upstream
  - name: gluon
    version: 0.9.6
    repository: oci://registry1.dso.mil/bigbang
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Fluentd: 1.19.0
  helm.sh/images: |
    - name: fluentd
      image: registry1.dso.mil/ironbank/opensource/fluentd/fluentd-kubernetes-daemonset:1.19.0
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Find upstream helm chart changelog and release notes here](https://github.com/fluent/helm-charts/releases)
    - [Find upstream application changelog and release notes here](https://github.com/fluent/fluentd/releases)